# What is Artifical Neural Netwook:

Artificial Neural Network (ANN) is a type of machine learning model inspired by the biological structure and function of the human brain. It consists of layers of interconnected nodes or neurons that process and transmit information to make predictions or classifications based on input data.

A real-time example of ANN is image recognition, where the network learns to recognize patterns in visual data and classify them accordingly. For instance, a neural network can be trained to identify objects in images, such as identifying cars, trees, and people, among others.

Another example is in natural language processing (NLP), where neural networks can be trained to understand and generate human language. This can be used for applications such as voice recognition, chatbots, and language translation, among others.

ANNs are also used in finance for predicting stock prices and in medical diagnosis for identifying potential diseases based on symptoms and patient data. Overall, ANNs are widely used in various industries for a range of applications, including fraud detection, customer segmentation, and recommendation systems.

1.What is an Artificial Neural Network and how does it work?

     An Artificial Neural Network is a type of machine learning model inspired by the structure and function of the human brain. It consists of layers of interconnected nodes or neurons that process and transmit information to make predictions or classifications based on input data.

2.What are the different types of activation functions used in Neural Networks?

    Some of the commonly used activation functions in Neural Networks are sigmoid, ReLU, tanh, and softmax.
    
3.What are the different types of layers present in a typical Neural Network?

    A typical Neural Network consists of three types of layers: input layer, hidden layer, and output layer.
    
4.What is the backpropagation algorithm, and how does it help train Neural Networks?

    Backpropagation is an algorithm used to train Neural Networks by calculating the error gradient of the output and propagating it back through the layers to adjust the weights and biases of the neurons. This helps the network to learn and improve its predictions.
    
5.How do you choose the number of hidden layers and nodes in a Neural Network?

    The number of hidden layers and nodes in a Neural Network depends on the complexity of the problem, the size of the dataset, and the available computational resources. Generally, it is recommended to start with a small number of hidden layers and nodes and gradually increase them until the desired performance is achieved.
    
6.What is regularization, and how is it used in Neural Networks?

    Regularization is a technique used to prevent overfitting in Neural Networks. It involves adding a penalty term to the cost function, which helps to control the complexity of the model and improve its generalization performance.
    
7.What are some common challenges when training Neural Networks, and how can you overcome them?

    Some common challenges when training Neural Networks are overfitting, vanishing gradients, and selection of appropriate hyperparameters. These challenges can be overcome by using regularization techniques, optimizing the learning rate, and selecting appropriate activation functions and architectures.

8.How can you assess the performance of a Neural Network, and what metrics do you use?

    The performance of a Neural Network can be assessed using metrics such as accuracy, precision, recall, F1 score, and AUC-ROC score. These metrics evaluate the model's ability to correctly classify the input data and provide a measure of its overall performance.

9.What is overfitting in Neural Networks, and how can you prevent it?

    Overfitting is a common problem in Neural Networks where the model fits the training data too closely and fails to generalize well to new data. To prevent overfitting, techniques such as regularization, early stopping, and dropout can be used.
    
10.What is transfer learning, and how is it applied in Neural Networks?

    Transfer learning is a technique in machine learning where a pre-trained model is used as a starting point for a new model. In Neural Networks, transfer learning can be used to leverage the knowledge learned by a pre-trained model on a similar task and fine-tune it for a new task.
    
11.What are Convolutional Neural Networks, and what types of problems are they best suited for?

    Convolutional Neural Networks (CNNs) are a type of Neural Network commonly used in image processing and computer vision tasks. They are best suited for problems involving image recognition, object detection, and segmentation.
    
12.How are Recurrent Neural Networks different from other types of Neural Networks, and what types of problems are they best suited for?

    Recurrent Neural Networks (RNNs) are a type of Neural Network commonly used in sequence modeling tasks such as natural language processing and speech recognition

# Import the Required Libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.10.0'

# Part 1

# Data Preprocessing:

In [3]:
data = pd.read_csv('Churn_Modelling.csv')

In [4]:
data

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [5]:
X = data.iloc[:,3:-1].values
Y = data.iloc[:,-1].values

In [6]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [7]:
print(Y)

[1 0 1 ... 1 1 0]


# Encoding the Categorical data

Label Encoding the 'Gender' column

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [9]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


# One Hot Encoding the 'Geography' column

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [11]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Splitting the dataset into training and testing

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2,random_state = 0)

In [13]:
print(X_train)

[[0.0 0.0 1.0 ... 1 0 163830.64]
 [0.0 1.0 0.0 ... 1 1 57098.0]
 [1.0 0.0 0.0 ... 1 0 185630.76]
 ...
 [1.0 0.0 0.0 ... 1 0 181429.87]
 [0.0 0.0 1.0 ... 1 1 148750.16]
 [0.0 1.0 0.0 ... 1 0 118855.26]]


In [14]:
print(X_test)

[[0.0 1.0 0.0 ... 1 1 192852.67]
 [1.0 0.0 0.0 ... 1 0 128702.1]
 [0.0 0.0 1.0 ... 1 1 75732.25]
 ...
 [0.0 0.0 1.0 ... 1 0 141533.19]
 [0.0 1.0 0.0 ... 1 1 11276.48]
 [0.0 1.0 0.0 ... 1 0 192950.6]]


In [15]:
print(Y_train)

[0 0 0 ... 0 0 1]


In [16]:
print(Y_test)

[0 1 0 ... 0 0 0]


# Feature Scaling

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [18]:
print(X_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


In [19]:
print(X_test)

[[-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
   1.61085707]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   0.49587037]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   0.71888467]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -1.54507805]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   1.61255917]]


# Paert 2: Buildling the ANN model

Initializing the ANN

In [20]:
ann = tf.keras.models.Sequential()

Adding the input Layer and First Hidden Layer

In [21]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

Adding Second Hidden Layer

In [22]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

Adding the output Layer

In [23]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

# Part 3: Traing the ANN

Compiling the ANN

In [24]:
ann.compile(optimizer = 'adam', loss ='binary_crossentropy' ,metrics = ['accuracy'])

Training the ANN on the Traing set

In [25]:
ann.fit(X_train,Y_train,batch_size = 32,epochs = 100)

Epoch 1/100
250/250 [==============================] - 5s 2ms/step - loss: 0.5381 - accuracy: 0.7960
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4850 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4611 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4459 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4375 - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4322 - accuracy: 0.8035
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4288 - accuracy: 0.8125
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4257 - accuracy: 0.8165
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4228 - accuracy: 0.8207
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4203 - accura

250/250 [==============================] - 1s 2ms/step - loss: 0.3492 - accuracy: 0.8558
Epoch 82/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3480 - accuracy: 0.8560
Epoch 83/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3476 - accuracy: 0.8575
Epoch 84/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3466 - accuracy: 0.8559
Epoch 85/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3457 - accuracy: 0.8593
Epoch 86/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3452 - accuracy: 0.8589
Epoch 87/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3445 - accuracy: 0.8585
Epoch 88/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3443 - accuracy: 0.8580
Epoch 89/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3441 - accuracy: 0.8580
Epoch 90/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3439 - accuracy: 

# Making the Predictions and Evaluating the Model

Predict the Result of Single Observation

Homework:

Solution:

In [26]:
print(ann.predict(sc.transform([[1,0,0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))

1/1 [==============================] - 0s 296ms/step
[[0.01762086]]


In [27]:
print(ann.predict(sc.transform([[1,0,0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))>0.5)

1/1 [==============================] - 1s 866ms/step
[[False]]


# Predict the test set result

In [29]:
y_pred = ann.predict(X_test)
y_pred = (y_pred >0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


# Making the Confusion Matrix:

In [30]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, y_pred)
print(cm)
accuracy_score(Y_test,y_pred)

[[1519   76]
 [ 200  205]]


0.862